In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

In [3]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
dataset_url = '/content/drive/MyDrive/contents/skin-disease-datasaet/train_set'

In [5]:
import os

In [6]:
os.listdir(dataset_url)


['BA-impetigo',
 'BA- cellulitis',
 'VI-chickenpox',
 'PA-cutaneous-larva-migrans',
 'FU-nail-fungus',
 'FU-athlete-foot',
 'FU-ringworm',
 'VI-shingles']

In [7]:
import pathlib
data_dir=pathlib.Path(dataset_url)
data_dir

PosixPath('/content/drive/MyDrive/contents/skin-disease-datasaet/train_set')

In [8]:
cellulitis=list(data_dir.glob('BA- cellulitis/*'))
len(cellulitis)

136

In [9]:
VI_chickenpoxt=list(data_dir.glob('VI-chickenpox/*'))
len(VI_chickenpoxt)

136

In [10]:
FU_athlete_foot=list(data_dir.glob('FU-athlete-foot/*'))
len(FU_athlete_foot)

124

In [11]:
VI_shingles=list(data_dir.glob('VI-shingles/*'))
len(VI_shingles)


130

In [12]:
FU_nail_fungus=list(data_dir.glob('FU-nail-fungus/*'))
len(FU_nail_fungus)

129

In [13]:
BA_impetigo=list(data_dir.glob('BA-impetigo/*'))
len(BA_impetigo)

80

In [14]:
FU_ringworm=list(data_dir.glob('FU-ringworm/*'))
len(FU_ringworm)

90

In [15]:
PA_cutaneous_larva_migrans=list(data_dir.glob('PA-cutaneous-larva-migrans/*'))
len(PA_cutaneous_larva_migrans)

100

In [18]:
disease_images_train_dic={
    'cellulitis':list(data_dir.glob('BA- cellulitis/*')),
    'impetigo':list(data_dir.glob('BA-impetigo/*')),
    'athlete-foot':list(data_dir.glob('FU-athlete-foot/*')),
    'nail-fungus':list(data_dir.glob('FU-nail-fungus/*')),
    'ringworm':list(data_dir.glob('FU-ringworm/*')),
    'cutaneous-larva-migrans':list(data_dir.glob('PA-cutaneous-larva-migrans/*')),
    'chickenpox':list(data_dir.glob('VI-chickenpox/*')),
    'shingles':list(data_dir.glob('VI-shingles/*')),
#     'normal':list(data_dir.glob('normal/*')),
}

In [20]:
disease_train_label_dic={
    'cellulitis': 0,
    'impetigo': 1,
    'athlete-foot': 2,
    'nail-fungus': 3,
    'ringworm': 4,
    'cutaneous-larva-migrans':5,
    'chickenpox':6,
    'shingles':7,

}

In [22]:
import cv2

x_train = []
y_train = []

for image_name, image_paths in disease_images_train_dic.items():
    for image_path in image_paths:
        img = cv2.imread(str(image_path))
        if img is None:
            continue
        image_resize=cv2.resize(img,(224,224))
        x_train.append(image_resize)
        y_train.append(disease_train_label_dic[image_name])


In [23]:
x_train[0].shape


(224, 224, 3)

In [24]:
len(x_train)


925

In [25]:
len(y_train)


925

In [26]:
y_train=np.array(y_train)
x_train=np.array(x_train)
y_train.shape

(925,)

In [28]:
dataset_url='/content/drive/MyDrive/contents/skin-disease-datasaet/test_set'


In [29]:
import pathlib
data_dir=pathlib.Path(dataset_url)
data_dir

PosixPath('/content/drive/MyDrive/contents/skin-disease-datasaet/test_set')

In [30]:
disease_images_test_dic={
    'cellulitis':list(data_dir.glob('BA- cellulitis/*')),
    'impetigo':list(data_dir.glob('BA-impetigo/*')),
    'athlete-foot':list(data_dir.glob('FU-athlete-foot/*')),
    'nail-fungus':list(data_dir.glob('FU-nail-fungus/*')),
    'ringworm':list(data_dir.glob('FU-ringworm/*')),
    'cutaneous-larva-migrans':list(data_dir.glob('PA-cutaneous-larva-migrans/*')),
    'chickenpox':list(data_dir.glob('VI-chickenpox/*')),
    'shingles':list(data_dir.glob('VI-shingles/*')),
#     'normal':list(data_dir.glob('test_set/normal/*')),
}
disease_test_label_dic={
    'cellulitis': 0,
    'impetigo': 1,
    'athlete-foot': 2,
    'nail-fungus': 3,
    'ringworm': 4,
    'cutaneous-larva-migrans':5,
    'chickenpox':6,
    'shingles':7,
#     'normal':8,
}

In [31]:
x_test = []
y_test = []

for image_name, image_paths in disease_images_test_dic.items():
    for image_path in image_paths:
        img = cv2.imread(str(image_path))
        if img is None:
            continue
        image_resize=cv2.resize(img,(224,224))
        x_test.append(image_resize)
        y_test.append(disease_test_label_dic[image_name])

In [32]:
x_train=np.array(x_train)
y_train=np.array(y_train)
x_test=np.array(x_test)
y_test=np.array(y_test)

In [33]:
x_test.shape


(234, 224, 224, 3)

In [34]:
x_train_scaled=x_train/255
x_test_scaled=x_test/255

In [35]:
x_train_scaled[1]


array([[[0.25098039, 0.10588235, 0.02745098],
        [0.25490196, 0.10980392, 0.03137255],
        [0.25490196, 0.09803922, 0.02352941],
        ...,
        [0.0627451 , 0.08235294, 0.0745098 ],
        [0.04705882, 0.06666667, 0.05882353],
        [0.02352941, 0.04313725, 0.03529412]],

       [[0.2627451 , 0.11764706, 0.03921569],
        [0.25490196, 0.10980392, 0.03137255],
        [0.2627451 , 0.10588235, 0.03137255],
        ...,
        [0.04705882, 0.06666667, 0.05882353],
        [0.05098039, 0.07058824, 0.0627451 ],
        [0.03529412, 0.05490196, 0.04705882]],

       [[0.28235294, 0.1254902 , 0.05098039],
        [0.2745098 , 0.11764706, 0.04313725],
        [0.2627451 , 0.10588235, 0.03137255],
        ...,
        [0.07058824, 0.09019608, 0.08235294],
        [0.0627451 , 0.08235294, 0.0745098 ],
        [0.06666667, 0.08627451, 0.07843137]],

       ...,

       [[0.40784314, 0.42745098, 0.39215686],
        [0.37647059, 0.39607843, 0.36078431],
        [0.38039216, 0

In [36]:
import tensorflow_hub as hub


In [37]:
feature_extractor_url = "https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4"
feature_extractor_layer = hub.KerasLayer(feature_extractor_url,
                                         input_shape=(224, 224, 3),
                                         trainable=False)

In [38]:
x_train_scaled.shape


(925, 224, 224, 3)

In [39]:
model=keras.Sequential(
    [
        feature_extractor_layer,
        keras.layers.Dense(9,activation='softmax')
    ]
)
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics='accuracy',
)
model.fit(x_train_scaled,y_train,epochs=20)

Epoch 1/20
29/29 [==============================] - 39s 1s/step - loss: 1.4817 - accuracy: 0.5005
Epoch 2/20
29/29 [==============================] - 31s 1s/step - loss: 0.5154 - accuracy: 0.8659
Epoch 3/20
29/29 [==============================] - 31s 1s/step - loss: 0.3094 - accuracy: 0.9384
Epoch 4/20
29/29 [==============================] - 31s 1s/step - loss: 0.2173 - accuracy: 0.9676
Epoch 5/20
29/29 [==============================] - 30s 1s/step - loss: 0.1626 - accuracy: 0.9816
Epoch 6/20
29/29 [==============================] - 31s 1s/step - loss: 0.1276 - accuracy: 0.9881
Epoch 7/20
29/29 [==============================] - 30s 1s/step - loss: 0.1005 - accuracy: 0.9946
Epoch 8/20
29/29 [==============================] - 30s 1s/step - loss: 0.0825 - accuracy: 0.9946
Epoch 9/20
29/29 [==============================] - 30s 1s/step - loss: 0.0684 - accuracy: 0.9989
Epoch 10/20
29/29 [==============================] - 31s 1s/step - loss: 0.0589 - accuracy: 1.0000
Epoch 11/20
29/29 [

In [40]:
model.evaluate(x_test_scaled,y_test)


8/8 [==============================] - 10s 1s/step - loss: 0.1021 - accuracy: 0.9701


[0.10213087499141693, 0.9700854420661926]

In [42]:
y_predict=model.predict(x_test_scaled)
# y_predict[0]
y_predicted_labels=[]
for i in y_predict:
    y_predicted_labels.append(np.argmax(i))

y_predicted_labels=np.array(y_predicted_labels)

8/8 [==============================] - 8s 909ms/step


In [43]:
from sklearn.metrics import confusion_matrix, classification_report
print("Classification Report: \n", classification_report(y_test, y_predicted_labels))

Classification Report: 
               precision    recall  f1-score   support

           0       0.97      0.94      0.96        34
           1       1.00      1.00      1.00        20
           2       0.97      0.97      0.97        32
           3       0.97      1.00      0.99        33
           4       0.96      0.96      0.96        23
           5       0.96      0.92      0.94        25
           6       1.00      0.97      0.99        34
           7       0.94      1.00      0.97        33

    accuracy                           0.97       234
   macro avg       0.97      0.97      0.97       234
weighted avg       0.97      0.97      0.97       234



In [44]:
confusion_matrix=tf.math.confusion_matrix(labels=y_test,predictions=y_predicted_labels)
confusion_matrix

<tf.Tensor: shape=(8, 8), dtype=int32, numpy=
array([[32,  0,  0,  0,  1,  1,  0,  0],
       [ 0, 20,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 31,  1,  0,  0,  0,  0],
       [ 0,  0,  0, 33,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 22,  0,  0,  1],
       [ 1,  0,  1,  0,  0, 23,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 33,  1],
       [ 0,  0,  0,  0,  0,  0,  0, 33]], dtype=int32)>

In [46]:
model.save('my_model.h5')

In [57]:
import torch
from torchvision import models
import torch.nn as nn
from keras.models import Sequential

In [56]:
pip install onnx onnxruntime tf2onnx


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 29.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 47.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 455.8/455.8 kB 32.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 5.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 9.1 MB/s eta 0:00:00
